services:
  - type: web
    name: training-online-portal
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

